name = "bark-cfworker-proxy"
main = "server.js"
compatibility_date = "2026-01-31"

[vars]
UPSTREAM_BASE = "https://api.day.app"

[observability]
[observability.logs]
enabled = false
invocation_logs = false

[[routes]]
pattern = "bark-cfw-proxy.kagurazakairis.xyz"
custom_domain = true